import MainPage from "@/components/MainPage"
import Head from "next/head"


export default function Home() {
  return (
    <>
        <Head>
          <title>News App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" type="image/jpg" href="news.png"/>
        </Head>
      <MainPage/>
    </>
  )
}
