import Head from "next/head";
import Layout from "@/components/Layout/Layout";
import Categories from "@/components/HomePage/Categories";
import HomeArticle from "@/components/HomePage/HomeArticle";
import FullStory from "@/components/HomePage/FullStory";
import BigStory from "@/components/HomePage/BigStory";
import Popular from "@/components/HomePage/Popular";
import MostWatched from "@/components/HomePage/MostWatched";
import FindUs from "@/components/HomePage/FindUs";

type Props = {}

export default function MainPage({}: Props) {
  return (
    <>
        <Head>
          <title>News App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" type="image/jpg" href="news.png"/>
        </Head>
        <main className="grid lg:max-w-7xl mx-auto md:px-2">
        <Layout>
        <Categories/>
        <HomeArticle/>
        <FullStory/>
        <BigStory/>
        <Popular/>
        <MostWatched/>
        <FindUs/>
        </Layout>
      </main>
    </>
  );
};