import Head from "next/head";
import WeatherCard from "@/components/Weather/WeatherCard";
import CryptoCard from "@/components/Crypto/CryptoCard";
import NavBar from "@/components/Layout/Navbars/NavBar";
import NewsSection from '@/components/News/NewsSection';
import InfoBox from '@/components/News/InfoBox';

type Props = {}

export default function MainPage({}: Props) {
  return (
    <>
        <Head>
          <title>News App</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" type="image/jpg" href="news.png"/>
        </Head>
        <main className="grid gap-2 lg:gap-6 md:flex max-w-7xl mx-auto px-2">
        <NavBar/>
        <InfoBox/>
        <WeatherCard/>
        <NewsSection/>
        <CryptoCard/>
      </main>
    </>
  );
};